language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
  - rust: nightly
    env: CARGOFLAGS=--features alloc
cache: cargo
script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features